### ISSUE TITLE
How does a normal work day look like for you?

### ISSUE THREAD

**Issue by sindresorhus** [Rchristiani/ama#4]

**Comment by Rchristiani** [comment]
My work day varies. Since I am leading a 9 week course right now it is pretty hectic. I start the morning reviewing the content for the day, making changes here and there, and thinking of new questions to ask the students. 

Then I usually do a quick look at what is happening on twitter, hackernews or any newsletters that came in. Then I am usually teaching for a good 3-6 hours of the day. If there is project work time for the day, I get to work on some internal project, a workshop or maintenance for an existing project.  

But for the most part a lot of my development work happens at home off hours. Which is pretty nice, because it allows me to try things out on my terms and just build.
